# Generated by Django 4.2.4 on 2023-08-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcrm',
            name='comment_binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order', verbose_name='Order'),
        ),
    ]
